---
- name: Install pip package for handling xml
  pip:
    name: lxml
    state: present

- name: create module directory
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ wildfly_home }}/modules/system/layers/base/com'
    - '{{ wildfly_home }}/modules/system/layers/base/com/microsoft'
    - '{{ wildfly_home }}/modules/system/layers/base/com/microsoft/sqlserver'

- name: check if Module com.postgresql file is created
  stat:
    path: '{{ wildfly_home }}/modules/system/layers/base/com/microsoft/sqlserver/module.xml'
  register: sqlServerTest

- name: download postgresql jdbc driver
  get_url:
    url: "http://central.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/6.4.0.jre8/mssql-jdbc-6.4.0.jre8.jar"
    dest: "{{ wildfly_home }}/modules/system/layers/base/com/microsoft/sqlserver/mssql-jdbc-6.4.0.jre8.jar"
    mode: 0644
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
  when: sqlServerTest.stat.exists == False

- name: creating module definition
  template:
    src: mssql_module.xml.j2
    dest: '{{ wildfly_home }}/modules/system/layers/base/com/microsoft/sqlserver/module.xml'
    owner: '{{ wildfly_user }}'
    group: '{{ wildfly_group }}'
    mode: 0644

- name: Configure datasource in standalone.xml file
  xml:
    file: "{{wildfly_home}}/standalone/configuration/standalone.xml"
    xpath: //ds:subsystem/ds:datasources
    namespaces:
      ds: 'urn:jboss:domain:datasources:5.0'
    set_children:
      - datasource:
          jndi-name: "java:jboss/datasources/ExampleDS"
          pool-name: ExampleDS
          _:
            - connection-url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
            - driver: h2
            - pool:
                _:
                  - min-pool-size: '10'
                  - max-pool-size: '20'
                  - prefill: 'true'
            - security:
                _:
                  - user-name: sa
                  - password: sa
      - datasource:
          jndi-name: "{{ wildfly__datasource.jndi_name }}"
          pool-name: "{{ wildfly__datasource.pool_name }}"
          _:
            - connection-url: "{{ wildfly__datasource.connection_url }}"
            - driver: "{{ wildfly__datasource.driver_name }}"
            - pool:
                _:
                  - max-pool-size: "5"
                  - max-pool-size: "50"
                  # - prefill: "false"
                  - use-strict-min: "false"
                  # - flush-strategy: "FailingConnectionOnly"
            - security:
                _:
                  - user-name: "{{ wildfly__database_username }}"
                  - password: "{{ wildfly__database_password }}"
            # - validation:
            #     _:
            #       - valid-connection-checker:
            #           class-name: org.jboss.jca.adapters.jdbc.extensions.mssql.MSSQLValidConnectionChecker
      - drivers:
          _:
            - driver:
                name: "h2"
                module: "com.h2database.h2"
                _:
                  - xa-datasource-class: 'org.h2.jdbcx.JdbcDataSource'
            - driver:
                name: "{{ wildfly__datasource.driver_name }}"
                module: "{{ wildfly__datasource.driver_module }}"
                _:
                  - driver-class: '{{ wildfly__datasource.driver_class_name }}'
  notify: restart wildfly
