wildfly_url: ftp://servismt01.servis.justice.cz/wildfly-14.0.1.Final.tar.gz
wildfly_home: '/opt/wildfly'
wildfly_user: gitlab_deploy
wildfly_group: deployers

wildfly_app_name: wildfly
wildfly__reverse_proxy: False
wildfly__generate_certificate: True #allow to create the certificates
wildfly__enable_ssl: True
wildfly__kerberos: False


# Defining datasource
wildfly__database_server_port: localhost:4666
wildfly__database_db: "{{ wildfly_app_name }}"
wildfly__database_username: "{{ wildfly_app_name }}"
wildfly__database_password: "{{ wildfly_app_name }}"
wildfly__datasource:
  connection_url: "jdbc:sqlserver://{{ wildfly__database_server_port }};databaseName={{wildfly__database_db}}"
  jndi_name: "java:/{{ wildfly_app_name }}"
  pool_name: "{{ wildfly_app_name }}"
  driver_name: sqlserver
  driver_module: com.microsoft
  driver_class_name: com.microsoft.sqlserver.jdbc.SQLServerDriver
