wildfly_url: ftp://servismt01.servis.justice.cz/wildfly-14.0.1.Final.tar.gz
wildfly_home: '/opt/wildfly'
wildfly_user: gitlab_deploy
wildfly_group: deployers

wildfly_app_name: wildfly
wildfly__reverse_proxy: False
wildfly__generate_certificate: True #allow to create the certificates
wildfly__enable_ssl: True
wildfly__kerberos: False
